import { FilmDepartment } from "@/types/portfolio";

export interface FilmDepartmentMeta {
  id: FilmDepartment;
  label: string;
  headTitle: string;
  subRoles: string[];
  guilds: string[];
  description: string;
  kitCategories: string[];
  sampleRoles: string[];
}

export const FILM_DEPARTMENTS: FilmDepartmentMeta[] = [
  {
    id: "directing",
    label: "Directing",
    headTitle: "Director",
    subRoles: ["Director", "1st Assistant Director (1st AD)", "2nd Assistant Director (2nd AD)", "2nd 2nd AD", "Script Supervisor"],
    guilds: ["Directors Guild of America (DGA)"],
    description: "Visionary leadership, shot list execution, on-set time management, and script continuity.",
    kitCategories: ["Director's Viewfinder", "Monitors", "Script Supervision Rig", "Walkies & Headsets"],
    sampleRoles: ["Feature Film Director", "Commercial Director", "1st AD", "Script Supervisor"],
  },
  {
    id: "production",
    label: "Production",
    headTitle: "Producer / UPM",
    subRoles: ["Executive Producer", "Producer", "Line Producer", "Unit Production Manager (UPM)", "Production Coordinator", "1st Assistant Production Coordinator"],
    guilds: ["Producers Guild of America (PGA)", "DGA (UPM)"],
    description: "Financing, scheduling, budget administration, permits, insurance, and overall production logistics.",
    kitCategories: ["Production Office Rigs", "Call Sheet Systems", "Budgeting Software"],
    sampleRoles: ["Line Producer", "UPM", "Production Coordinator"],
  },
  {
    id: "camera",
    label: "Camera & Cinematography",
    headTitle: "Director of Photography (DP)",
    subRoles: ["Director of Photography", "Camera Operator (A Cam / B Cam)", "1st AC (Focus Puller)", "2nd AC (Clapper Loader)", "Digital Imaging Technician (DIT)", "Steadicam / Trinity Operator", "Drone Pilot"],
    guilds: ["International Cinematographers Guild (ICG Local 600)", "ASC", "BSC"],
    description: "Visual storytelling, optics, camera movement, sensor exposure, color spaces, and camera prep.",
    kitCategories: ["Camera Bodies & Sensors", "Cinema Prime & Zoom Lenses", "Wireless Follow Focus", "DIT Color Carts", "Steadicam & Gimbals"],
    sampleRoles: ["Director of Photography", "Camera Operator", "1st AC (Focus Puller)", "DIT"],
  },
  {
    id: "electric_lighting",
    label: "Lighting & Electric",
    headTitle: "Gaffer (Chief Lighting Technician)",
    subRoles: ["Gaffer", "Best Boy Electric", "Rigging Gaffer", "Best Boy Rigging Electric", "Lighting Board Operator (Dimmer Board)", "Juicer / Electrician", "Generator Operator"],
    guilds: ["IATSE Local 728 (Motion Picture Lighting)"],
    description: "Power distribution, lighting setups, color temperature, fixture rigging, and DMX wireless control.",
    kitCategories: ["LED Fixtures (SkyPanels, Titan Tubes)", "HMI & Tungsten Fresnels", "Distribution Boxes & Camloks", "DMX Consoles & CRMX Transmitters", "Generator Packages"],
    sampleRoles: ["Best Boy Electric", "Gaffer", "Lighting Board Op", "Rigging Gaffer"],
  },
  {
    id: "grip",
    label: "Grip & Rigging",
    headTitle: "Key Grip",
    subRoles: ["Key Grip", "Best Boy Grip", "Dolly Grip", "Rigging Key Grip", "Best Boy Rigging Grip", "Company Grip / Hammer", "Crane / Jib Operator"],
    guilds: ["IATSE Local 80 (Grips, Crafts Service)"],
    description: "Camera support, shaping and diffusing light, safety rigging, overhead frames, cranes, and vehicle mounts.",
    kitCategories: ["5-Ton / 10-Ton Grip Trucks", "Dollies (Chapman, Fisher)", "Overhead Rags & Frames", "C-Stands & Combo Stands", "Speedrail & Car Rigging Kits"],
    sampleRoles: ["Key Grip", "Best Boy Grip", "Dolly Grip", "Rigging Grip"],
  },
  {
    id: "sound",
    label: "Sound & Audio",
    headTitle: "Production Sound Mixer",
    subRoles: ["Production Sound Mixer", "Boom Operator", "Sound Utility", "Sound Designer", "Supervising Sound Editor", "Re-Recording Mixer", "Foley Artist"],
    guilds: ["IATSE Local 695", "Cinema Audio Society (CAS)", "MPSE"],
    description: "Crystal-clear dialog capture, multitrack recording, RF frequency coordination, boom mic choreography, and spatial sound design.",
    kitCategories: ["Multitrack Field Recorders (Sound Devices)", "Wireless Lav Rigs (Lectrosonics, Wisycom)", "Shotgun & Hypercardioid Mics (Schoeps, Sennheiser)", "RF Distribution & Antennas", "Sound Carts & Bag Rigs"],
    sampleRoles: ["Production Sound Mixer", "Boom Operator", "Sound Designer"],
  },
  {
    id: "art_department",
    label: "Art & Production Design",
    headTitle: "Production Designer",
    subRoles: ["Production Designer", "Art Director", "Set Decorator", "Leadman", "Set Dresser", "Property Master", "Assistant Prop Master", "Armorer", "Construction Coordinator"],
    guilds: ["Art Directors Guild (ADG Local 800)", "IATSE Local 44 (Props, Set Dressing)"],
    description: "Architectural visual design, period accuracy, set decoration, hero props, weapons handling, and graphic design.",
    kitCategories: ["Drafting & 3D CAD Tools", "Prop Toolkits & Hero Cases", "Set Dressing Kits", "Scenic Painting & Aging Kits"],
    sampleRoles: ["Production Designer", "Art Director", "Prop Master", "Set Decorator"],
  },
  {
    id: "costume",
    label: "Costume & Wardrobe",
    headTitle: "Costume Designer",
    subRoles: ["Costume Designer", "Assistant Costume Designer", "Costume Supervisor", "Key Costumer", "Set Costumer", "Agier / Dyer"],
    guilds: ["Costume Designers Guild (CDG Local 892)", "IATSE Local 705 (Motion Picture Costumers)"],
    description: "Character silhouette, fabric sourcing, period tailoring, multiples for stunts, and on-set continuity maintenance.",
    kitCategories: ["Wardrobe Sewing Rigs", "Breakdown & Aging Kits", "Steamer & On-Set Wardrobe Carts"],
    sampleRoles: ["Costume Designer", "Costume Supervisor", "Set Costumer"],
  },
  {
    id: "hair_makeup",
    label: "Hair & Makeup",
    headTitle: "Makeup Department Head",
    subRoles: ["Makeup Department Head", "Key Makeup Artist", "Hair Department Head", "Key Hair Stylist", "Special Effects (SFX) Makeup Artist", "Prosthetics Specialist"],
    guilds: ["Make-up Artists & Hair Stylists Guild (IATSE Local 706)"],
    description: "Screen cosmetics, HD skin prep, period hairstyles, wound/trauma prosthetics, tattoos, and character transformation.",
    kitCategories: ["Airbrush Systems", "Silicone Prosthetics Lab", "High-Definition Makeup Rigs", "Wig & Hair Styling Stations"],
    sampleRoles: ["Makeup Dept Head", "Key Hair Stylist", "SFX Prosthetics Artist"],
  },
  {
    id: "stunts",
    label: "Stunts & Action",
    headTitle: "Stunt Coordinator",
    subRoles: ["Stunt Coordinator", "Assistant Stunt Coordinator", "Stunt Double", "Precision Driver", "Stunt Rigger", "Fight Choreographer"],
    guilds: ["SAG-AFTRA (Stunts)"],
    description: "High-octane physical choreography, wirework, fire burns, high falls, vehicular chases, and rigorous set safety.",
    kitCategories: ["Wire Rigs & Decelerators", "Crash Pads & Airbags", "Tactical Body Armor & Pads", "Fire Retardant Gear"],
    sampleRoles: ["Stunt Coordinator", "Fight Choreographer", "Precision Driver"],
  },
  {
    id: "vfx",
    label: "Visual Effects (VFX)",
    headTitle: "VFX Supervisor",
    subRoles: ["VFX Supervisor", "On-Set VFX Data Wrangler", "VFX Producer", "Lead Compositor", "3D / CG Lead", "Matchmove Artist"],
    guilds: ["Visual Effects Society (VES)"],
    description: "On-set chrome/grey ball HDRI capture, lidar scans, photogrammetry, green/blue screen supervision, and seamless post-compositing.",
    kitCategories: ["Lidar Scanners & Photogrammetry", "HDRI Panoramic Camera Rigs", "Tracking Markers & Witness Cams", "Nuke & Unreal Engine Pipelines"],
    sampleRoles: ["VFX Supervisor", "On-Set Data Wrangler", "Lead Compositor"],
  },
  {
    id: "editorial",
    label: "Editorial & Post-Production",
    headTitle: "Film Editor",
    subRoles: ["Lead Film Editor", "Additional Editor", "1st Assistant Editor", "Post Production Supervisor", "Finishing Colorist", "Conform Artist"],
    guilds: ["Motion Picture Editors Guild (IATSE Local 700)", "ACE (American Cinema Editors)"],
    description: "Narrative pacing, assembly, rough cut refinement, EDL/XML conforms, and precision HDR/ACES color grading.",
    kitCategories: ["Avid Media Composer / Premiere Suites", "DaVinci Resolve Advanced Color Panels", "Calibrated 4K HDR Reference Monitors", "SAN/NAS Storage Arrays"],
    sampleRoles: ["Lead Film Editor", "Finishing Colorist", "Assistant Editor"],
  },
  {
    id: "locations",
    label: "Locations",
    headTitle: "Location Manager",
    subRoles: ["Location Manager", "Assistant Location Manager (ALM)", "Location Scout", "Location Assistant"],
    guilds: ["Teamsters Local 399"],
    description: "Securing filming permits, neighborhood notifications, basecamp logistics, parking, and environmental preservation.",
    kitCategories: ["Scouting Camera & Drone Kits", "Basecamp Cones & Signage", "Location Power & Sanitation"],
    sampleRoles: ["Location Manager", "Location Scout", "Assistant Location Manager"],
  },
  {
    id: "casting",
    label: "Casting",
    headTitle: "Casting Director",
    subRoles: ["Casting Director", "Associate Casting Director", "Casting Assistant", "Extras / Background Casting Director"],
    guilds: ["Casting Society of America (CSA)", "Teamsters Local 399"],
    description: "Script breakdown, character role pitching, talent scouting, audition taping, chemistry reads, and actor deal negotiations.",
    kitCategories: ["Self-Tape & Audition Studio Rigs", "Breakdown Services & Eco-Cast", "Actor Dossiers & Databases"],
    sampleRoles: ["Casting Director", "Associate Casting Director", "Background Casting Director"],
  },
  {
    id: "music_scoring",
    label: "Music & Score",
    headTitle: "Film Composer",
    subRoles: ["Film Composer", "Music Supervisor", "Music Editor", "Score Orchestrator", "Scoring Mixer"],
    guilds: ["Society of Composers & Lyricists (SCL)", "ASCAP", "BMI", "The Recording Academy"],
    description: "Thematic leitmotifs, orchestral arrangements, sync licensing clearances, score recording, and stem mixing.",
    kitCategories: ["Orchestral Virtual Instrument Rigs", "Analogue Modular Synthesizers", "Dolby Atmos 7.1.4 Mix Studio", "Score Cue Software"],
    sampleRoles: ["Film Composer", "Music Supervisor", "Score Mixer"],
  },
  {
    id: "acting",
    label: "Acting / Cast",
    headTitle: "Lead Actor",
    subRoles: ["Lead Actor", "Supporting Actor", "Guest Star", "Recurring Character", "Voiceover / ADR Artist", "Motion Capture Performer"],
    guilds: ["SAG-AFTRA", "Actors' Equity (AEA)"],
    description: "Emotional resonance, dramatic intensity, comedic timing, character development, dialogue delivery, and physical embodiment.",
    kitCategories: ["Casting Showreel Suites", "Headshot Portfolios", "VO Whisper Rooms & Mic Kits"],
    sampleRoles: ["Dramatic Lead", "Character Actor", "Voiceover Specialist"],
  },
];

export const ALL_FILM_GUILDS = [
  "IATSE Local 728 (Lighting & Electric)",
  "IATSE Local 80 (Grips & Crafts)",
  "ICG Local 600 (Cinematographers Guild)",
  "IATSE Local 695 (Sound & Video)",
  "IATSE Local 700 (Motion Picture Editors Guild)",
  "IATSE Local 44 (Affiliated Property / Art Dept)",
  "IATSE Local 705 (Motion Picture Costumers)",
  "IATSE Local 706 (Make-up Artists & Hair Stylists)",
  "Art Directors Guild (ADG Local 800)",
  "Costume Designers Guild (CDG Local 892)",
  "Directors Guild of America (DGA)",
  "Screen Actors Guild (SAG-AFTRA)",
  "Producers Guild of America (PGA)",
  "Writers Guild of America (WGA)",
  "Teamsters Local 399 (Casting & Locations)",
  "Casting Society of America (CSA)",
  "American Society of Cinematographers (ASC)",
  "Cinema Audio Society (CAS)",
  "American Cinema Editors (ACE)",
  "Visual Effects Society (VES)",
  "Society of Composers & Lyricists (SCL)",
  "ASCAP / BMI / SESAC",
];
