import { PortfolioData } from "@/types/portfolio";

export const MUSICIAN_PRESET: PortfolioData = {
  profile: {
    stageName: "Abledsoul",
    discipline: "musician",
    tagline: "Industrial Metal & Experimental Darkwave Soundscapes",
    bio: "Abledsoul creates brutalist, high-impact industrial soundscapes combining crushing analog distortion, visceral polyrhythmic drums, and modular synthesis. Based in Los Angeles & touring internationally.",
    unions: ["ASCAP", "The Recording Academy / GRAMMYs"],
    primaryGenresOrTypes: ["Industrial Metal", "Darkwave", "Cyberpunk", "Noise Rock"],
    spotifyArtistUrl: "https://open.spotify.com/artist/4Z8W4fKeB5Yx6bu2Utwevm",
    bandcampArtistUrl: "https://abledsoil.bandcamp.com",
    youtubeChannelUrl: "https://youtube.com/@abledsoil",
    instagramHandle: "@abledsoil_sound",
    agentName: "Dominic Black",
    agencyName: "Obsidian Booking Global",
    bookingEmail: "booking@abledsoil.com",
    bookingPhone: "+1 (213) 555-0194",
    location: "Los Angeles, CA & Berlin",
    websiteUrl: "https://abledsoil.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-1",
      title: "Live at Hellfest Open Air - Full Stage Set",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      category: "live_performance",
      roleOrCharacter: "Lead Vocals & Synthesizers",
      duration: "04:15",
      uploadDate: "2026-02-14",
      thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
      description: "Headline stage performance featuring live visual mapping, analogue modular rigs, and 16-channel live monitoring.",
      isPrivate: false,
    },
    {
      id: "sr-2",
      title: "'Chrome Citadel' Official 4K Cinematic Music Video",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      category: "music_video",
      roleOrCharacter: "Producer & Composer",
      duration: "03:42",
      uploadDate: "2025-11-20",
      thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80",
      description: "Directed by Claire Chen. Nominated for Best Cinematography at Berlin Music Video Awards.",
      isPrivate: false,
    },
  ],
  discography: [
    {
      id: "disc-1",
      title: "Monolith of Ruin",
      releaseType: "Album",
      releaseDate: "2025-10-31",
      label: "Sub Rosa Soundworks",
      artworkUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
      spotifyUrl: "https://open.spotify.com/album/4Z8W4fKeB5Yx6bu2Utwevm",
      bandcampUrl: "https://abledsoil.bandcamp.com/album/monolith-of-ruin",
      upc: "840092182741",
      description: "10-track LP pressed on 180g blood-smoke vinyl. Mastered at Sterling Sound.",
      tracks: [
        { id: "tr-1", title: "Iron Siphon", duration: "03:52", isrc: "US-S4R-25-00101", audioPreviewUrl: "https://assets.mixkit.co/music/preview/mixkit-tech-house-vibes-130.mp3" },
        { id: "tr-2", title: "Cold Reactor Core", duration: "04:18", isrc: "US-S4R-25-00102", audioPreviewUrl: "https://assets.mixkit.co/music/preview/mixkit-heavy-metal-rock-lead-loop-817.mp3" },
        { id: "tr-3", title: "Rust & Neon", duration: "05:04", isrc: "US-S4R-25-00103" },
      ],
    },
    {
      id: "disc-2",
      title: "Subterfuge (Remixes)",
      releaseType: "EP",
      releaseDate: "2026-01-15",
      label: "Independent",
      artworkUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80",
      tracks: [
        { id: "tr-4", title: "Subterfuge (Modular Overdrive Mix)", duration: "06:12" },
        { id: "tr-5", title: "Subterfuge (Ambient Drone Dub)", duration: "07:44" },
      ],
    },
  ],
  headshots: [
    {
      id: "hs-1",
      imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "300 DPI 4K Master",
      photographerCredit: "Lukas Weber (Berlin)",
      year: "2026",
      isPrimary: true,
      caption: "Official Press Portrait - Studio Lighting with Ana-Digi Distortion",
    },
    {
      id: "hs-2",
      imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=85",
      shotType: "live_stage",
      resolution: "300 DPI 4K Master",
      photographerCredit: "Sarah Jenkins Photography",
      year: "2025",
      isPrimary: false,
      caption: "Live stage capture under high-contrast strobes",
    },
  ],
};

export const ACTOR_PRESET: PortfolioData = {
  profile: {
    stageName: "Marcus Vance",
    discipline: "actor",
    tagline: "SAG-AFTRA Dramatic Actor & Screen Combat Specialist",
    bio: "Marcus Vance is a classically trained screen and stage performer known for gritty dramatic roles, psychological thrillers, and intense physical acting. Graduate of Juilliard Drama Division.",
    unions: ["SAG-AFTRA", "Actors' Equity Association (AEA)"],
    primaryGenresOrTypes: ["Dramatic Lead", "Psychological Thriller", "Detective / Law Enforcement", "Screen Combat"],
    imdbUrl: "https://www.imdb.com/name/nm0000001/",
    instagramHandle: "@marcusvance_actor",
    youtubeChannelUrl: "https://youtube.com/@marcusvancereels",
    agentName: "Vivian Sterling",
    agencyName: "Sterling Theatrical Artists Agency (LA & London)",
    bookingEmail: "theatrical@sterlingartists.com",
    bookingPhone: "+1 (310) 555-0812",
    location: "New York, NY / Los Angeles, CA",
    websiteUrl: "https://marcusvance.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-act-1",
      title: "2026 Theatrical & Dramatic Screen Reel",
      url: "https://vimeo.com/76979871",
      category: "dramatic",
      roleOrCharacter: "Lead - Det. Joseph Graves in 'The Hollow Wire'",
      duration: "02:45",
      uploadDate: "2026-01-10",
      thumbnailUrl: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80",
      description: "Clips from HBO limited series and award-winning Sundance premiere. Contains intense dialogue and screen combat sequences.",
      isPrivate: false,
    },
    {
      id: "sr-act-2",
      title: "Commercial & Dark Comedy Reel",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      category: "commercial",
      roleOrCharacter: "National Campaign Spokesman & Dark Comedy Lead",
      duration: "01:30",
      uploadDate: "2025-09-18",
      thumbnailUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
      description: "Fast-paced commercial comedic timing and deadpan deliveries for national automotive and luxury timepiece spots.",
      isPrivate: false,
    },
  ],
  discography: [],
  headshots: [
    {
      id: "hs-act-1",
      imageUrl: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "300 DPI 4K Print-Ready",
      photographerCredit: "Michael Grecco Studios (NYC)",
      year: "2026",
      isPrimary: true,
      caption: "Primary Theatrical Headshot - High Contrast Studio Lighting",
    },
    {
      id: "hs-act-2",
      imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85",
      shotType: "commercial",
      resolution: "300 DPI 4K Print-Ready",
      photographerCredit: "Michael Grecco Studios (NYC)",
      year: "2026",
      isPrimary: false,
      caption: "Commercial & Television Headshot - Warm Editorial",
    },
    {
      id: "hs-act-3",
      imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85",
      shotType: "dramatic_closeup",
      resolution: "300 DPI 4K Print-Ready",
      photographerCredit: "Elena Rostova (London)",
      year: "2025",
      isPrimary: false,
      caption: "Character Portrait - Period Drama & Thriller Casting",
    },
  ],
};

export const DUAL_CREATOR_PRESET: PortfolioData = {
  profile: {
    stageName: "Elena Cruz",
    discipline: "dual",
    tagline: "Film Composer, Cellist & Cinematic Screen Performer",
    bio: "Elena Cruz bridges cinema scoring and on-screen dramatic performances. Dual SAG-AFTRA and ASCAP member specializing in original neo-classical compositions, dark orchestral textures, and period film roles.",
    unions: ["SAG-AFTRA", "ASCAP", "Society of Composers & Lyricists (SCL)"],
    primaryGenresOrTypes: ["Film Score", "Neo-Classical", "Dark Cinematic Drama", "Sci-Fi Lead"],
    imdbUrl: "https://www.imdb.com/name/nm0000002/",
    spotifyArtistUrl: "https://open.spotify.com/artist/elena_cruz",
    bandcampArtistUrl: "https://elenacruz.bandcamp.com",
    youtubeChannelUrl: "https://youtube.com/@elenacruzcinema",
    instagramHandle: "@elenacruz_music",
    agentName: "Arthur Pendelton",
    agencyName: "Creative Artists Management (London & LA)",
    bookingEmail: "representation@cruzcreative.com",
    bookingPhone: "+1 (310) 555-4921",
    location: "London, UK / Los Angeles, CA",
    websiteUrl: "https://elenacruz.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-dual-1",
      title: "Cinematic Film Scoring & Spotting Reel",
      url: "https://vimeo.com/76979871",
      category: "dramatic",
      roleOrCharacter: "Original Score & Solo Cellist",
      duration: "03:15",
      uploadDate: "2026-01-22",
      thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=800&q=80",
      description: "Cues scored for psychological thrillers and BAFTA-nominated indie dramas.",
      isPrivate: false,
    },
    {
      id: "sr-dual-2",
      title: "On-Screen Dramatic Acting Reel",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      category: "dramatic",
      roleOrCharacter: "Supporting Lead - Sofia in 'Winter Nocturne'",
      duration: "02:20",
      uploadDate: "2025-10-15",
      thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
      description: "English & French bilingual dialogue from European co-productions.",
      isPrivate: false,
    },
  ],
  discography: [
    {
      id: "disc-dual-1",
      title: "Aetheria (Original Motion Picture Soundtrack)",
      releaseType: "Soundtrack",
      releaseDate: "2025-12-05",
      label: "Sony Masterworks / Milan",
      artworkUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
      spotifyUrl: "https://open.spotify.com/album/aetheria_ost",
      tracks: [
        { id: "tr-d1", title: "Opening Elegy for Cello & Tape", duration: "03:22", audioPreviewUrl: "https://assets.mixkit.co/music/preview/mixkit-tech-house-vibes-130.mp3" },
        { id: "tr-d2", title: "The Frozen Observatory", duration: "04:45" },
        { id: "tr-d3", title: "Crawl Into Daylight", duration: "05:10" },
      ],
    },
  ],
  headshots: [
    {
      id: "hs-dual-1",
      imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "300 DPI 4K Print-Ready",
      photographerCredit: "Henri Blanc Studio (Paris)",
      year: "2026",
      isPrimary: true,
      caption: "Theatrical Portrait with Antique Venetian Cello",
    },
  ],
};

export const BEST_BOY_ELECTRIC_PRESET: PortfolioData = {
  profile: {
    stageName: "Jack 'Volt' Callahan",
    discipline: "film_crew",
    filmDepartment: "electric_lighting",
    filmRole: "Best Boy Electric / Gaffer",
    yearsExperience: "14 Years on Set",
    dayRateGuideline: "IATSE Local 728 Scale + Box Rental / Kit Fee ($950/10hr + $150 kit)",
    tagline: "IATSE Local 728 Best Boy Electric & Gaffer | High-Voltage Distro & LED Wireless DMX",
    bio: "Jack Callahan is a veteran IATSE Local 728 Best Boy Electric and Gaffer with over 14 years on Tier 1-3 features, episodic television, and major studio tentpoles. Expert in large-scale generator tie-ins, 3-phase power distribution, wireless CRMX networks, and complex LED fixture automation.",
    unions: ["IATSE Local 728 (Motion Picture Lighting Technicians)"],
    primaryGenresOrTypes: ["Narrative Features", "Prestige Streaming Series", "High-Concept Sci-Fi", "Studio Action"],
    imdbUrl: "https://www.imdb.com",
    vimeoUrl: "https://vimeo.com",
    instagramHandle: "@jackvolt_lighting",
    agentName: "Danielle Vance",
    agencyName: "Illumination Crew Representation LA",
    bookingEmail: "jack.callahan.lighting@gmail.com",
    bookingPhone: "+1 (818) 555-0149",
    location: "Los Angeles, CA / Atlanta, GA",
    websiteUrl: "https://jackcallahan.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-bbe-1",
      title: "Feature Lighting & DMX Rigging Breakdown",
      url: "https://vimeo.com/76979871",
      category: "lighting_gaffer",
      roleOrCharacter: "Best Boy Electric & Board Op",
      duration: "03:40",
      uploadDate: "2026-01-10",
      thumbnailUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80",
      description: "Night exterior and industrial warehouse lighting setup: 4x 18K Arrimaxes on condors, 24x Astera Titan Tubes on wireless CRMX, 1200A twin-pack generator distro.",
      isPrivate: false,
    },
    {
      id: "sr-bbe-2",
      title: "Commercial & Stage Lighting Reel",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      category: "lighting_gaffer",
      roleOrCharacter: "Gaffer",
      duration: "02:15",
      uploadDate: "2025-11-05",
      thumbnailUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=800&q=80",
      description: "Studio soundstage lighting with custom softbox rigs, Arri SkyPanel S360s, and high-speed flicker-free ballast tuning.",
      isPrivate: false,
    },
  ],
  discography: [],
  headshots: [
    {
      id: "hs-bbe-1",
      imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "4K Master Portrait",
      photographerCredit: "On-Set Stills by Sarah Kim",
      year: "2026",
      isPrimary: true,
      caption: "On set with wireless DMX control tablet and light meter",
    },
  ],
  equipmentKit: [
    { id: "eq-1", name: "1200A 3-Phase Camlok Distro Package", category: "lighting", description: "Bates, lunchboxes, stingers, 4/0 feeder cable", isAvailableForRent: true },
    { id: "eq-2", name: "Astera Titan Tube 8-Way Charging Box", category: "lighting", description: "Full wireless CRMX transmitter with ART7 AsteraBox", isAvailableForRent: true },
    { id: "eq-3", name: "4x Arri SkyPanel S60-C Complete Kit", category: "lighting", description: "Chimeras, 40-degree honeycombs, center mounts", isAvailableForRent: true },
    { id: "eq-4", name: "Sekonic Speedmaster C-800 Spectrometer", category: "lighting", description: "CRI, SSI, and Kelvin color temperature measurement", isAvailableForRent: true },
    { id: "eq-5", name: "ETC Nomad 1024 DMX Lighting Console", category: "lighting", description: "Surface Pro rig with wireless router and iPad control", isAvailableForRent: true },
  ],
  filmCredits: [
    { id: "fc-1", title: "Apex Protocol (Feature)", year: "2025", role: "Best Boy Electric", department: "electric_lighting", productionCompany: "Warner Bros / Legendary", directorOrDP: "DP: Marcus Alvarez, ASC", festivalAwards: "Theatrical Release 2026", isFeatured: true },
    { id: "fc-2", title: "Midnight Corridor (Season 2)", year: "2025", role: "Best Boy Electric", department: "electric_lighting", productionCompany: "HBO Max Originals", directorOrDP: "Gaffer: Leo Stern", isFeatured: true },
    { id: "fc-3", title: "Neon Horizon (Indie Feature)", year: "2024", role: "Gaffer", department: "electric_lighting", productionCompany: "A24 / Ghostlight", directorOrDP: "DP: Elena Rostova", festivalAwards: "Sundance 2025 Official Selection", isFeatured: true },
  ],
};

export const KEY_GRIP_PRESET: PortfolioData = {
  profile: {
    stageName: "Travis 'Rig' Henderson",
    discipline: "film_crew",
    filmDepartment: "grip",
    filmRole: "Key Grip / Best Boy Grip",
    yearsExperience: "16 Years on Set",
    dayRateGuideline: "IATSE Local 80 Scale ($920/10hr + 5-Ton Grip Truck Package)",
    tagline: "IATSE Local 80 Key Grip & Dolly Specialist | Technocrane, Peewee IV & Precision Vehicle Mounts",
    bio: "Travis Henderson is a Master Key Grip and member of IATSE Local 80 with 16 years of experience overseeing complex camera movement, precision rigging, and dynamic lighting diffusion on feature films and high-speed automotive commercials.",
    unions: ["IATSE Local 80 (Motion Picture Grips)"],
    primaryGenresOrTypes: ["Action Features", "Automotive Commercials", "Steep Terrain / Stunt Rigging", "Soundstage Period Dramas"],
    imdbUrl: "https://www.imdb.com",
    vimeoUrl: "https://vimeo.com",
    instagramHandle: "@henderson_keygrip",
    bookingEmail: "travis.grip@hendersonrigs.com",
    bookingPhone: "+1 (818) 555-0821",
    location: "Los Angeles, CA / Albuquerque, NM",
    websiteUrl: "https://hendersongrip.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-kg-1",
      title: "TechnoCrane & High-Speed Car Rigging Reel",
      url: "https://vimeo.com/76979871",
      category: "grip_rigging",
      roleOrCharacter: "Key Grip",
      duration: "03:10",
      uploadDate: "2026-02-01",
      thumbnailUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
      description: "Hostess tray, hood mounts, Peewee dolly track moves, and 45-foot Technocrane arm moves over mountain passes.",
      isPrivate: false,
    },
  ],
  discography: [],
  headshots: [
    {
      id: "hs-kg-1",
      imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "4K Master Portrait",
      photographerCredit: "Grip Truck Portrait by Mike Vance",
      year: "2026",
      isPrimary: true,
      caption: "Travis Henderson at the Chapman Peewee Dolly rig",
    },
  ],
  equipmentKit: [
    { id: "eq-g1", name: "5-Ton Custom Grip Truck Package", category: "grip", description: "Complete C-stands, combo stands, overhead rags (12x12, 20x20), pipe, speedrail", isAvailableForRent: true },
    { id: "eq-g2", name: "Chapman Peewee IV Camera Dolly", category: "grip", description: "Universal tracking wheels, 64ft precision straight/curved track", isAvailableForRent: true },
    { id: "eq-g3", name: "Modern Studio Speedrail Car Rigging Package", category: "grip", description: "Suction cups, cheese plates, hostesses trays, hood mounts", isAvailableForRent: true },
  ],
  filmCredits: [
    { id: "fc-g1", title: "Velocity Chase (Feature)", year: "2025", role: "Key Grip", department: "grip", productionCompany: "Universal Pictures", directorOrDP: "Dir: Christian Grey", isFeatured: true },
    { id: "fc-g2", title: "Iron Valley (Feature)", year: "2024", role: "Best Boy Grip", department: "grip", productionCompany: "Sony Pictures", isFeatured: true },
  ],
};

export const CINEMATOGRAPHER_PRESET: PortfolioData = {
  profile: {
    stageName: "Elena Rostova",
    discipline: "film_crew",
    filmDepartment: "camera",
    filmRole: "Director of Photography (DP)",
    yearsExperience: "11 Years / 7 Features",
    dayRateGuideline: "ICG Local 600 Commercial & Narrative Scale + Camera Kit",
    tagline: "ICG Local 600 Cinematographer | Narrative Features, Anamorphic Glass & Visual Poetry",
    bio: "Elena Rostova is an acclaimed Director of Photography based in Los Angeles and London. A member of ICG Local 600, her visual style blends rich filmic textures, naturalistic chiaroscuro lighting, and precise spatial camera movement. Her work has screened at Sundance, Cannes Un Certain Regard, and TIFF.",
    unions: ["ICG Local 600 (International Cinematographers Guild)", "BSC Guest Member"],
    primaryGenresOrTypes: ["Narrative Feature", "Psychological Thriller", "Auteur Drama", "High-End Commercial"],
    imdbUrl: "https://www.imdb.com",
    vimeoUrl: "https://vimeo.com",
    instagramHandle: "@rostova_dp",
    agentName: "Marcus Thorne",
    agencyName: "WME Agency (Camera & Directors Dept)",
    bookingEmail: "rostova.dop@gmail.com",
    bookingPhone: "+1 (310) 555-0931",
    location: "Los Angeles, CA / London, UK",
    websiteUrl: "https://elenarostova.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-dp-1",
      title: "Narrative Cinematography Showreel (4K Anamorphic)",
      url: "https://vimeo.com/76979871",
      category: "cinematography",
      roleOrCharacter: "Director of Photography",
      duration: "03:30",
      uploadDate: "2026-01-15",
      thumbnailUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
      description: "Selected scenes shot on Arri Alexa 35 and Cooke Anamorphic/i Full Frame Plus lenses. Color graded in ACES / DaVinci Resolve.",
      isPrivate: false,
    },
  ],
  discography: [],
  headshots: [
    {
      id: "hs-dp-1",
      imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "4K Master Portrait",
      photographerCredit: "David Leigh (London)",
      year: "2026",
      isPrimary: true,
      caption: "Elena Rostova operating the Arri Alexa 35 with Cooke 40mm Anamorphic",
    },
  ],
  equipmentKit: [
    { id: "eq-c1", name: "Arri Alexa 35 4.6K Super 35 Camera Package", category: "camera", description: "LPL/PL mount, Codex 2TB drives, SmallHD Cine 7 monitor", isAvailableForRent: true },
    { id: "eq-c2", name: "Cooke Anamorphic/i Full Frame Plus Prime Set", category: "camera", description: "32mm, 40mm, 50mm, 75mm, 100mm T2.3 primes", isAvailableForRent: true },
    { id: "eq-c3", name: "Teradek Bolt 4K MAX Wireless Video System", category: "camera", description: "1 TX, 2 RX with director's monitor cage", isAvailableForRent: true },
  ],
  filmCredits: [
    { id: "fc-c1", title: "The Obsidian Bell", year: "2025", role: "Director of Photography", department: "camera", productionCompany: "Film4 / A24", directorOrDP: "Dir: Claire Chen", festivalAwards: "Sundance Film Festival — Best Cinematography Award", isFeatured: true },
    { id: "fc-c2", title: "Winter Solitude", year: "2024", role: "Director of Photography", department: "camera", productionCompany: "BFI / BBC Film", festivalAwards: "Cannes Un Certain Regard Selection", isFeatured: true },
  ],
};

export const SOUND_MIXER_PRESET: PortfolioData = {
  profile: {
    stageName: "David 'Levels' Miller",
    discipline: "film_crew",
    filmDepartment: "sound",
    filmRole: "Production Sound Mixer / Sound Designer",
    yearsExperience: "18 Years on Set",
    dayRateGuideline: "IATSE Local 695 Scale ($950/10hr + 16-Track Sound Cart Rental)",
    tagline: "CAS / IATSE Local 695 Production Sound Mixer | 32-Track Redundant Digital Rig & Multichannel RF",
    bio: "David Miller is a Cinema Audio Society (CAS) and IATSE Local 695 Production Sound Mixer. Specializing in pristine dialog capture in demanding acoustic environments, multitrack timecode synchronization, and immersive spatial audio recording.",
    unions: ["Cinema Audio Society (CAS)", "IATSE Local 695 (Production Sound)"],
    primaryGenresOrTypes: ["Prestige Drama", "Action / Combat Sets", "Period Narrative", "Large Ensemble Casts"],
    imdbUrl: "https://www.imdb.com",
    bookingEmail: "david.sound.mixer@gmail.com",
    bookingPhone: "+1 (818) 555-0914",
    location: "Los Angeles, CA / New York, NY",
    websiteUrl: "https://davidmillersound.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-snd-1",
      title: "Production Sound & Dialog Capture Showcase",
      url: "https://vimeo.com/76979871",
      category: "sound_mix",
      roleOrCharacter: "Production Sound Mixer",
      duration: "02:45",
      uploadDate: "2026-01-20",
      thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80",
      description: "Demonstrating high-noise floor dialog rescue, RF coordination across 14 cast members, and wireless boom operation.",
      isPrivate: false,
    },
  ],
  discography: [],
  headshots: [
    {
      id: "hs-snd-1",
      imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "4K Master Portrait",
      year: "2026",
      isPrimary: true,
      caption: "David Miller at the Sound Devices 888 cart",
    },
  ],
  equipmentKit: [
    { id: "eq-s1", name: "Sound Devices 888 16-Channel / 24-Track Field Recorder", category: "sound", description: "Dante I/O, CL-16 fader controller, dual SSD redundancy", isAvailableForRent: true },
    { id: "eq-s2", name: "10x Wisycom MCR54 Quad Wireless Receivers & Bodypacks", category: "sound", description: "DPA 4060 and Sanken COS-11D lavalier microphones", isAvailableForRent: true },
    { id: "eq-s3", name: "Schoeps CMIT 5U & MiniCMIT Shotgun Microphones", category: "sound", description: "Cinela Pianissimo windshield suspensions and carbon boom poles", isAvailableForRent: true },
  ],
  filmCredits: [
    { id: "fc-s1", title: "The Last Horizon (Feature)", year: "2025", role: "Production Sound Mixer", department: "sound", productionCompany: "Searchlight Pictures", festivalAwards: "CAS Award Nominee for Outstanding Sound Mixing", isFeatured: true },
    { id: "fc-s2", title: "Shadow Line (Series)", year: "2024", role: "Production Sound Mixer", department: "sound", productionCompany: "Netflix", isFeatured: true },
  ],
};

export const DIRECTOR_PRESET: PortfolioData = {
  profile: {
    stageName: "Julian Solis",
    discipline: "film_crew",
    filmDepartment: "directing",
    filmRole: "Feature Film Director / Screenwriter",
    yearsExperience: "8 Years / 3 Features",
    dayRateGuideline: "DGA Theatrical Scale",
    tagline: "DGA Feature Film Director & Writer | Cannes Un Certain Regard & Sundance US Dramatic",
    bio: "Julian Solis is an independent filmmaker and member of the Directors Guild of America (DGA). Known for grounded psychological thrillers, tension-building pacing, and raw actor-driven storytelling.",
    unions: ["Directors Guild of America (DGA)", "Writers Guild of America (WGA)"],
    primaryGenresOrTypes: ["Psychological Thriller", "Neo-Noir", "Crime Drama", "Auteur Narrative"],
    imdbUrl: "https://www.imdb.com",
    vimeoUrl: "https://vimeo.com",
    agentName: "Sarah Lin",
    agencyName: "CAA (Motion Picture Literary)",
    bookingEmail: "julian@solisfilms.com",
    location: "Los Angeles, CA / New York, NY",
    websiteUrl: "https://juliansolis.alistwebs.com",
  },
  showreels: [
    {
      id: "sr-dir-1",
      title: "Directing Narrative Scene Anthology",
      url: "https://vimeo.com/76979871",
      category: "directing",
      roleOrCharacter: "Director",
      duration: "04:20",
      uploadDate: "2026-01-05",
      thumbnailUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
      description: "Directing excerpts featuring high-stakes interrogation scenes, quiet emotional climaxes, and single-take set pieces.",
      isPrivate: false,
    },
  ],
  discography: [],
  headshots: [
    {
      id: "hs-dir-1",
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=85",
      shotType: "theatrical",
      resolution: "4K Master Portrait",
      year: "2026",
      isPrimary: true,
      caption: "Julian Solis on set in 35mm monitor video village",
    },
  ],
  filmCredits: [
    { id: "fc-dir-1", title: "Fracture Point", year: "2025", role: "Director & Writer", department: "directing", productionCompany: "Neon / Topic Studios", festivalAwards: "Cannes Un Certain Regard Official Selection", isFeatured: true },
    { id: "fc-dir-2", title: "Blind River", year: "2023", role: "Director", department: "directing", productionCompany: "Independent", festivalAwards: "Sundance US Dramatic Grand Jury Nominee", isFeatured: true },
  ],
};

export const ALL_PRESETS: { id: string; label: string; department: string; data: PortfolioData }[] = [
  { id: "musician", label: "Musician / Darkwave Band (Abledsoul)", department: "Music & Sound", data: MUSICIAN_PRESET },
  { id: "actor", label: "Dramatic Screen Actor (Marcus Vance)", department: "Acting / Cast", data: ACTOR_PRESET },
  { id: "dual", label: "Dual Creator / Composer (Elena Cruz)", department: "Multi-Hyphenate", data: DUAL_CREATOR_PRESET },
  { id: "electric_lighting", label: "Best Boy Electric & Gaffer (Jack Callahan)", department: "Lighting & Electric", data: BEST_BOY_ELECTRIC_PRESET },
  { id: "grip", label: "Key Grip & Dolly Rig (Travis Henderson)", department: "Grip & Rigging", data: KEY_GRIP_PRESET },
  { id: "camera", label: "Cinematographer / DP (Elena Rostova)", department: "Camera & Optics", data: CINEMATOGRAPHER_PRESET },
  { id: "sound", label: "Production Sound Mixer (David Miller)", department: "Sound & Audio", data: SOUND_MIXER_PRESET },
  { id: "directing", label: "Feature Film Director (Julian Solis)", department: "Directing", data: DIRECTOR_PRESET },
];

