import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { db } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";
import { Site } from "@/types";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Loader2, Music, FileText } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { CreateSiteDocDialog } from "@/components/docs/CreateSiteDocDialog";

const PreviewPage = () => {
  const { siteId } = useParams();
  const navigate = useNavigate();
  const [site, setSite] = useState<Site | null>(null);
  const [loading, setLoading] = useState(true);
  const [isDocModalOpen, setIsDocModalOpen] = useState(false);

  useEffect(() => {
    const fetchSite = async () => {
      if (!siteId) return;
      try {
        const docRef = doc(db, "sites", siteId);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          setSite({ id: docSnap.id, ...docSnap.data() } as Site);
        } else {
          console.error("No such document!");
          navigate("/");
        }
      } catch (error) {
        console.error("Error fetching site:", error);
        navigate("/");
      }
      setLoading(false);
    };

    fetchSite();
  }, [siteId, navigate]);

  if (loading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-gold" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-gold/30">
      {/* Administrative Toolbar (Hidden in final export) */}
      <div className="fixed top-4 left-4 z-50 flex gap-2">
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => navigate("/")} 
          className="bg-black/50 border-white/10 text-white hover:bg-white/10 rounded-full"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Dashboard
        </Button>
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => setIsDocModalOpen(true)} 
          className="bg-black/60 border-blue-500/30 text-blue-400 hover:bg-blue-500/10 hover:text-blue-300 rounded-full"
        >
          <FileText className="w-4 h-4 mr-2" />
          Export to Google Docs
        </Button>
      </div>

      {/* Hero Section */}
      <section className="relative h-[80vh] flex items-center justify-center overflow-hidden border-b border-white/5">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-gold/10 via-transparent to-transparent" />
        <div className="container relative z-10 text-center space-y-6">
          <div className="inline-block p-3 rounded-full bg-gold/5 border border-gold/20 mb-4">
            <Music className="w-12 h-12 text-gold" />
          </div>
          <h1 className="text-6xl md:text-8xl font-display font-bold tracking-tighter text-white uppercase">
            {site?.name || "Untitled Site"}
          </h1>
          <p className="text-xl md:text-2xl text-white/60 max-w-2xl mx-auto font-light">
            Sovereign Digital Presence
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="py-24 container max-w-4xl">
        <div className="prose prose-invert prose-xl max-w-none">
          <div className="grid grid-cols-1 md:grid-cols-12 gap-12">
            <div className="md:col-span-4">
              <h2 className="text-gold font-display text-sm tracking-[0.2em] uppercase mb-4">The Blueprint</h2>
              <p className="text-sm text-white/40 leading-relaxed">
                Generated by A List Webs AI Designer for the Creative Sovereignty ecosystem.
              </p>
            </div>
            <div className="md:col-span-8 space-y-8">
               <div className="p-8 rounded-3xl bg-white/[0.02] border border-white/5 backdrop-blur-sm">
                <ReactMarkdown className="[&_h1]:text-white [&_h2]:text-white [&_h3]:text-white [&_strong]:text-gold [&_p]:text-white/70 [&_li]:text-white/60">
                  {site?.design_summary || ""}
                </ReactMarkdown>
              </div>
              
              <div className="pt-12 flex flex-wrap gap-4">
                <Button variant="hero" size="lg" className="rounded-full">
                  Book the Band
                </Button>
                <Button variant="outline" size="lg" className="rounded-full border-white/10">
                  Visit Merch Store
                </Button>
                <Button 
                  onClick={() => setIsDocModalOpen(true)}
                  size="lg" 
                  className="rounded-full bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 border border-blue-500/30 font-medium"
                >
                  <FileText className="w-4 h-4 mr-2 text-blue-400" />
                  Generate Google Doc Dossier
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-white/5 text-center">
        <p className="text-sm text-white/20 tracking-widest uppercase">
          Powered by A List Webs
        </p>
      </footer>

      {/* Google Docs Generator Modal */}
      <CreateSiteDocDialog
        open={isDocModalOpen}
        onOpenChange={setIsDocModalOpen}
        site={site}
      />
    </div>
  );
};

export default PreviewPage;